source 'http://rubygems.org'
source 'http://gems.alces-software.com'

gem 'alces-tools', '>= 0.13.0'
gem 'commander'
gem 'terminal-table'
gem 'rainbow'
# gem 'rugged', '~> 0.17.0.a'
gem 'grit'
gem 'dm-rest-adapter', '1.3.0.alces0'
gem 'rubytree'
gem 'dm-sqlite-adapter', '>= 1.2.0'
gem 'dm-migrations', '>= 1.2.0'
gem 'dm-aggregates', '>= 1.2.0'
gem 'memoist'

#group :development do
#  gem 'wirble'
#  gem 'pry'
#end
