#!/bin/bash

NAME=packager

# ensure all children die when we do
trap "/bin/kill -- -$BASHPID &>/dev/null" EXIT INT TERM

function toggle_spin () {
	if [ -z "$spin_pid" ]; then
	    (
		i=1
		sp="/-\|"
		printf " "
		while true;
		do
		    printf "\b[1m${sp:i++%${#sp}:1}[0m"
		    if [[ i -eq ${#sp} ]]; then
			i=0
		    fi
		    sleep 0.2
		done
	    ) &
	    sleep 1
	    spin_pid=$!
	else
	    sleep 1
	    kill $spin_pid
	    wait $spin_pid 2>/dev/null
	    printf "\b"
	    unset spin_pid
	fi
}

function title() {
    printf "\n > $1\n"
}

function doing() {
    if [ -z "$2" ]; then
	pad=12
    else
	pad=$2
    fi
    printf "    [36m%${pad}s[0m ... " "$1"
    toggle_spin
}

function say_done () {
    toggle_spin
    if [ $1 -gt 0 ]; then
	echo '[31mFAIL[0m'
	exit 1
    else
	echo '[32mOK[0m '
    fi
}

LOGDIR="var/log/${NAME}"

# Create initial configuration files
title "Updating configuration"
doing "Update"
if (( UID == 0 )); then
    cp -r "${alces_SRC_PATH}/${NAME}/etc/global"/* "${alces_PATH}/etc"
    cp -r "${alces_SRC_PATH}/${NAME}/etc/system"/* "${alces_PATH}/etc"
else
    cp -r "${alces_SRC_PATH}/${NAME}/etc/global"/* "${alces_PATH}/etc"
    cp -r "${alces_SRC_PATH}/${NAME}/etc/user"/* "${alces_PATH}/etc"
fi
say_done $?

title "Reinstalling '${NAME}' facility"
doing 'Reinstall'
rm -rf "${alces_PATH}/opt/${BASENAME}/lib/${NAME}"
cp -r "${alces_SRC_PATH}/${NAME}/lib" "${alces_PATH}/opt/${BASENAME}/lib/${NAME}"
say_done $?
doing 'Link'
for a in "${alces_PATH}/opt/${BASENAME}/lib/${NAME}/lib/actions"/*; do
  ln -sf $a "${alces_PATH}/opt/${BASENAME}/lib/actions"
done
say_done $?

# install ruby lib gems
title "Configuring ruby components"
cd "${alces_PATH}/opt/${BASENAME}/lib/${NAME}/lib/ruby"
doing 'Configure'
"${alces_RUBYHOME}/bin/bundle" install --local &> "${alces_PATH}/${LOGDIR}/components-install.log"
say_done $?

title "Updating gridware structure"
if (( UID == 0 )); then
    alces_GRIDWARE="/opt/gridware"
else
    alces_GRIDWARE="${HOME}/gridware"
fi
mkdir -p "${alces_GRIDWARE}/pkg" "${alces_GRIDWARE}/etc/modules" "${alces_GRIDWARE}/etc"
doing 'Configure'
cp -r "${alces_SRC_PATH}/${NAME}/dist/modules"/* "${alces_GRIDWARE}/etc/modules"
cp -r "${alces_SRC_PATH}/${NAME}/dist/plugins.d"/* "${alces_PATH}/etc/${BASENAME}/plugins.d"
if [ ! -d "${alces_GRIDWARE}/etc/repos" ]; then
  mv "${alces_PATH}/etc/repos" "${alces_GRIDWARE}/etc"
else
  rm -r "${alces_PATH}/etc/repos"
fi
cat <<EOF > "${alces_PATH}/var/lib/${NAME}/repos/base/repo.yml"
:source: $alces_BASE_REPO_PATH
EOF

# "$alces_RUBY" "${alces_SRC_PATH}/${NAME}/scripts/init.rb"
say_done $?

